name: catch_and_flow
description: A Flutter package for simplified and type-safe error handling in synchronous and asynchronous operations with a functional programming approach.
version: 1.0.0
homepage: https://github.com/camillobucciarelli/catch_and_flow

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0